#!/usr/bin/env bash
#
# Pre-Edit Hook for this operator
# Prevents editing generated files, vendored code, and high-risk files without warning
#
# Usage: Called automatically by Claude Code before file edits
#

set -euo pipefail

FILE="${1:-}"

if [[ -z "$FILE" ]]; then
  echo "Usage: $0 <file-path>"
  exit 1
fi

# Normalize file path to be repo-relative for consistent pattern matching
# This ensures patterns like vendor/* work regardless of whether the input is absolute or relative
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo ".")

# Reject absolute paths outside the repo
if [[ "$FILE" = /* ]]; then
  if [[ ! "$FILE" == "$REPO_ROOT"/* ]]; then
    echo "❌ ERROR: File path is outside repository: $FILE"
    exit 1
  fi
  # Convert absolute path to repo-relative
  FILE="${FILE#"$REPO_ROOT"/}"
fi

# Canonicalize and reject traversal segments
if command -v realpath >/dev/null 2>&1; then
  CANONICAL=$(realpath -s --relative-to="$REPO_ROOT" "$FILE" 2>/dev/null || echo "")
  if [[ -z "$CANONICAL" ]] || [[ "$CANONICAL" == *".."* ]]; then
    echo "❌ ERROR: Invalid file path (contains traversal): $FILE"
    exit 1
  fi
  FILE="$CANONICAL"
fi

# Strip leading ./
FILE="${FILE#./}"

# Helper function for interactive confirmation
confirm_or_exit() {
  local prompt="$1"
  echo "$prompt"

  # Check if stdin is a TTY (interactive terminal)
  if [[ ! -t 0 ]]; then
    echo "❌ ERROR: Non-interactive environment detected"
    echo "   This operation requires manual confirmation"
    echo "   Run this script in an interactive terminal"
    exit 1
  fi

  read -r response
  if [[ ! "$response" =~ ^[Yy]$ ]]; then
    exit 1
  fi
}

# =============================================================================
# GENERATED FILES - BLOCK EDITS
# =============================================================================

# Check for generated Go files
if [[ "$FILE" == *"zz_generated."* ]]; then
  echo "❌ BLOCKED: Cannot edit generated file: $FILE"
  echo "   This file is auto-generated by controller-gen."
  echo "   To regenerate: boilerplate/_lib/container-make generate"
  exit 1
fi

if [[ "$FILE" == *"/generated/"* ]] && [[ "$FILE" == *"mock_"* ]]; then
  echo "❌ BLOCKED: Cannot edit generated mock: $FILE"
  echo "   This file is auto-generated by mockgen."
  echo "   To regenerate: boilerplate/_lib/container-make generate"
  exit 1
fi

# Check for generated CRD manifests
if [[ "$FILE" == deploy/crds/* ]] && [[ "$FILE" == *.yaml ]]; then
  echo "⚠️  WARNING: Editing generated CRD manifest: $FILE"
  echo "   CRDs are generated from API types."
  echo "   Consider editing api/v1alpha1/*.go instead."
  echo "   To regenerate CRDs: make manifests"
  echo ""
  confirm_or_exit "   Continue? (y/N)"
fi

# =============================================================================
# LOCKFILES - WARNING
# =============================================================================

if [[ "$FILE" == "go.sum" ]]; then
  echo "⚠️  WARNING: Editing go.sum directly"
  echo "   This file is managed by 'go mod tidy'."
  confirm_or_exit "   Are you sure you want to edit it manually? (y/N)"
fi

# =============================================================================
# VENDORED CODE - BLOCK EDITS
# =============================================================================

if [[ "$FILE" == vendor/* ]]; then
  echo "❌ BLOCKED: Cannot edit vendored code: $FILE"
  echo "   Vendor directory is managed by go modules."
  echo "   Update dependencies in go.mod instead."
  exit 1
fi

if [[ "$FILE" == boilerplate/* ]] && [[ "$FILE" != boilerplate/update* ]]; then
  echo "⚠️  WARNING: Editing boilerplate file: $FILE"
  echo "   Boilerplate is managed upstream."
  echo "   Local changes may be overwritten by 'make boilerplate-update'."
  confirm_or_exit "   Continue? (y/N)"
fi

# =============================================================================
# HIGH-RISK FILES - WARNING
# =============================================================================

HIGH_RISK_PATTERNS=(
  "*/rbac.go"
  "*/auth*.go"
  "*_rbac.yaml"
  "*/networkpolicy*.go"
  "*ClusterRole*.yaml"
  ".tekton/*.yaml"
  "build/Dockerfile"
)

for pattern in "${HIGH_RISK_PATTERNS[@]}"; do
  # shellcheck disable=SC2053
  if [[ "$FILE" == $pattern ]]; then
    echo "⚠️  HIGH-RISK FILE: $FILE"
    echo "   This file affects security or CI/CD."
    echo "   Changes require:"
    echo "   - Careful review"
    echo "   - Test coverage"
    echo "   - Security validation"
    echo ""
    confirm_or_exit "   Continue? (y/N)"
    break
  fi
done

# =============================================================================
# LARGE DIFFS - WARNING
# =============================================================================

# If file exists and is large, warn about broad changes
if [[ -f "$FILE" ]]; then
  LINES=$(wc -l < "$FILE")
  if (( LINES > 500 )); then
    echo "⚠️  LARGE FILE: $FILE ($LINES lines)"
    echo "   Prefer targeted edits over broad refactors."
    confirm_or_exit "   Continue? (y/N)"
  fi
fi

# All checks passed
exit 0
