apiVersion: v1
kind: ServiceAccount
metadata:
  name: certman-operator
  namespace: {{.config.namespace}}
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
