apiVersion: v1
kind: Template
metadata:
  name: olm-artifacts-template

parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  value: staging
- name: IMAGE_TAG
  value: latest
- name: REPO_DIGEST
  value: latest

objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: certman-operator-catalog
  spec:
    sourceType: grpc
    image: ${REPO_DIGEST}
    displayName: certman-operator Registry
    publisher: SRE 

- apiVersion: operators.coreos.com/v1alpha2
  kind: OperatorGroup
  metadata:
    name: certman-operator-og
  spec:
    targetNamespaces:
    - certman-operator

- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: certman-operator
  spec:
    channel: ${CHANNEL}
    name: certman-operator
    source: certman-operator-catalog
    sourceNamespace: certman-operator
