apiVersion: v1
kind: Template
metadata:
  name: olm-artifacts-template

parameters:
- name: REGISTRY_IMG
  required: true
- name: IMAGE_DIGEST
  required: true
- name: CHANNEL
  value: staging
- name: FEDRAMP
  value: "false"
- name: HOSTED_ZONE_ID
  value: ""

objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: certman-operator-catalog
  spec:
    sourceType: grpc
    grpcPodConfig:
      securityContextConfig: restricted
    image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
    displayName: certman-operator Registry
    publisher: SRE 

- apiVersion: operators.coreos.com/v1alpha2
  kind: OperatorGroup
  metadata:
    name: certman-operator-og
  spec:
    targetNamespaces:
    - certman-operator

- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: certman-operator
  spec:
    channel: ${CHANNEL}
    name: certman-operator
    source: certman-operator-catalog
    sourceNamespace: certman-operator
    config:
      env:
      - name: FEDRAMP
        value: "${FEDRAMP}"
      - name: HOSTED_ZONE_ID
        value: ${HOSTED_ZONE_ID}
