apiVersion: v1
kind: Template
parameters:
  - name: CHANNEL
    required: false
  - name: PKO_IMAGE
    required: true
  - name: OPERATOR_IMAGE
    required: true
  - name: IMAGE_TAG
    required: true
  - name: REPO_NAME
    value: certman-operator-stage
    required: true
  - name: FEDRAMP
    value: "false"
metadata:
  name: selectorsyncset-template
objects:
  - apiVersion: package-operator.run/v1alpha1
    kind: ClusterPackage
    metadata:
      name: "${REPO_NAME}"
      annotations:
        package-operator.run/collision-protection: IfNoController
    spec:
      image: ${PKO_IMAGE}:${IMAGE_TAG}
      config:
        image: ${OPERATOR_IMAGE}:${IMAGE_TAG}
        env:
        - name: FEDRAMP
          value: "${FEDRAMP}"
