apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certman-operator-leader-election
  namespace: certman-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: certman-operator-leader-election
subjects:
- kind: ServiceAccount
  name: certman-operator
  namespace: certman-operator
