apiVersion: v1
kind: Service
metadata:
  labels:
    name: certman-operator
    release: monitoring
  name: certman-operator
  namespace: certman-operator
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: certman-operator
  sessionAffinity: None
  type: ClusterIP

