// THIS FILE IS GENERATED BY BOILERPLATE. DO NOT EDIT.
//go:build osde2e
// +build osde2e

package osde2etests

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/go-logr/logr"
	openshiftapi "github.com/openshift/api"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// E2EClientOption configures an E2EClient during construction.
// Use WithScheme to register operator-specific CRD types.
type E2EClientOption func(*e2eClientConfig) error

// e2eClientConfig holds options accumulated before client creation.
type e2eClientConfig struct {
	extraSchemes []func(*runtime.Scheme) error
}

// WithScheme returns an option that registers additional types with the
// client's runtime.Scheme. Each operator calls this to add its own CRD
// types without editing this boilerplate file.
//
// Example:
//
//	c, err := NewE2EClient(log, WithScheme(myoperatorv1.AddToScheme))
func WithScheme(addToScheme func(*runtime.Scheme) error) E2EClientOption {
	return func(cfg *e2eClientConfig) error {
		cfg.extraSchemes = append(cfg.extraSchemes, addToScheme)
		return nil
	}
}

// E2EClient wraps controller-runtime's client.Client with convenience
// methods for OSD operator e2e tests. It replaces the osde2e-common
// dependency entirely.
type E2EClient struct {
	client.Client
	config *rest.Config
	log    logr.Logger
}

// NewE2EClient creates an E2EClient by loading kubeconfig from the
// KUBECONFIG env var (falling back to ~/.kube/config). Pass WithScheme
// options to register operator-specific CRD types.
func NewE2EClient(log logr.Logger, opts ...E2EClientOption) (*E2EClient, error) {
	cfg, err := loadKubeConfig()
	if err != nil {
		return nil, fmt.Errorf("failed to load kubeconfig: %w", err)
	}
	return NewE2EClientFromConfig(cfg, log, opts...)
}

// NewE2EClientFromConfig creates an E2EClient from an explicit
// rest.Config. The base scheme always includes core/v1, apps/v1, and
// the OpenShift API types. Pass WithScheme options to register
// additional types (e.g. operator CRDs).
func NewE2EClientFromConfig(cfg *rest.Config, log logr.Logger, opts ...E2EClientOption) (*E2EClient, error) {
	var ecfg e2eClientConfig
	for _, opt := range opts {
		if err := opt(&ecfg); err != nil {
			return nil, fmt.Errorf("failed to apply client option: %w", err)
		}
	}

	scheme := runtime.NewScheme()

	// Register base types that every OSD operator test needs.
	if err := corev1.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("failed to register core/v1: %w", err)
	}
	if err := appsv1.AddToScheme(scheme); err != nil {
		return nil, fmt.Errorf("failed to register apps/v1: %w", err)
	}
	if err := openshiftapi.Install(scheme); err != nil {
		return nil, fmt.Errorf("failed to register openshift api: %w", err)
	}

	// Register operator-specific types supplied via WithScheme.
	for _, addToScheme := range ecfg.extraSchemes {
		if err := addToScheme(scheme); err != nil {
			return nil, fmt.Errorf("failed to register extra scheme: %w", err)
		}
	}

	c, err := client.New(cfg, client.Options{Scheme: scheme})
	if err != nil {
		return nil, fmt.Errorf("failed to create controller-runtime client: %w", err)
	}
	return &E2EClient{Client: c, config: cfg, log: log}, nil
}

// Get wraps client.Get with positional name/namespace args for API
// compatibility with the old osde2e-common openshift.Client.
func (c *E2EClient) Get(ctx context.Context, name, namespace string, obj client.Object) error {
	return c.Client.Get(ctx, types.NamespacedName{Name: name, Namespace: namespace}, obj)
}

// GetScheme returns the client's runtime.Scheme.
func (c *E2EClient) GetScheme() *runtime.Scheme {
	return c.Client.Scheme()
}

// GetConfig returns the rest.Config used by this client.
func (c *E2EClient) GetConfig() *rest.Config {
	return c.config
}

// Impersonate returns a new E2EClient that acts as the given user and
// groups. The "system:authenticated" and "system:authenticated:oauth"
// groups are added automatically when user is non-empty.
func (c *E2EClient) Impersonate(user string, groups ...string) (*E2EClient, error) {
	if user != "" {
		groups = append(groups, "system:authenticated", "system:authenticated:oauth")
	}
	impersonatedCfg := rest.CopyConfig(c.config)
	impersonatedCfg.Impersonate = rest.ImpersonationConfig{UserName: user, Groups: groups}
	return NewE2EClientFromConfig(impersonatedCfg, c.log)
}

const (
	metadataConfigMap = "osd-cluster-metadata"
	configNamespace   = "openshift-config"
)

// getClusterMetadata reads the osd-cluster-metadata configmap from the
// openshift-config namespace.
func (c *E2EClient) getClusterMetadata(ctx context.Context) (map[string]string, error) {
	var cm corev1.ConfigMap
	if err := c.Get(ctx, metadataConfigMap, configNamespace, &cm); err != nil {
		return nil, err
	}
	return cm.Data, nil
}

// IsSTS returns true if the cluster is configured with STS (Security
// Token Service) authentication.
func (c *E2EClient) IsSTS(ctx context.Context) (bool, error) {
	data, err := c.getClusterMetadata(ctx)
	if err != nil {
		return false, err
	}
	return data["api.openshift.com_sts"] == "true", nil
}

// GetProvider returns the cloud provider name from cluster metadata
// (e.g. "aws", "gcp").
func (c *E2EClient) GetProvider(ctx context.Context) (string, error) {
	data, err := c.getClusterMetadata(ctx)
	if err != nil {
		return "", err
	}
	return data["hive.openshift.io_cluster-platform"], nil
}

// GetRegion returns the cloud region from cluster metadata (e.g.
// "us-east-1").
func (c *E2EClient) GetRegion(ctx context.Context) (string, error) {
	data, err := c.getClusterMetadata(ctx)
	if err != nil {
		return "", err
	}
	return data["hive.openshift.io_cluster-region"], nil
}

// loadKubeConfig loads a rest.Config from the KUBECONFIG environment
// variable. If KUBECONFIG is not set, it falls back to
// ~/.kube/config.
func loadKubeConfig() (*rest.Config, error) {
	kubeconfig := os.Getenv("KUBECONFIG")
	if kubeconfig == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return nil, err
		}
		kubeconfig = filepath.Join(home, ".kube", "config")
	}
	return clientcmd.BuildConfigFromFlags("", kubeconfig)
}
